version: "3.5"
services:
  mosquitto:
    image: eclipse-mosquitto
    expose:
      - "1883"
    ports:
      - "1883:1883"
  mongo-db:
    image: mongo
    hostname: mongo-db
    container_name: mongo-db
    expose:
      - "27017"
    ports:
      - "27017:27017"